const source=await fetch('demo-state.json').then(r=>r.json());const id=()=>crypto.randomUUID();
let d;try{d=JSON.parse(sessionStorage.getItem('onelearn-demo-data')||'null')}catch{}if(!d){const pupil={id:id(),first:'Amelia',last:'Bennett',year:12,login_code:'DEMO',access_code:'SF-DEMO',gcse_notes:'Example student',archived:false};d={mis:source.mis,revision:0,assignments:[],progress:[],sixth:{role:'admin',settings:{school_name:'Example Academy Sixth Form',choices_open:true},subjects:source.subjects,students:[pupil],classes:source.subjects.flatMap(s=>[12,13,14].map(year=>({id:id(),subject_id:s.id,year,section:1,room:'A01',capacity:24}))),enrolments:[],notices:[{id:id(),title:'Welcome to sixth form',body:'Explore your choices and classes in this demo.',published:true,year:null,created_at:new Date().toISOString()}],attendance:[]}};for(const sid of ['history','film','business','english-lit','maths'])d.sixth.enrolments.push({student_id:pupil.id,class_id:d.sixth.classes.find(c=>c.subject_id===sid&&c.year===12).id});d.assignments.push({id:id(),class_id:d.mis.students[0].classIds[0],title:'A little number practice',due_at:new Date(Date.now()+604800000).toISOString(),question_ids:source.questions.slice(0,4).map(q=>q.id),archived:false})}
const save=()=>{sessionStorage.setItem('onelearn-demo-data',JSON.stringify(d))};
const own=()=>({...d.sixth,student:d.sixth.students[0],classes:d.sixth.classes.filter(c=>d.sixth.enrolments.some(e=>e.student_id===d.sixth.students[0].id&&e.class_id===c.id))});
export async function demoRPC(n,a={}){let r;switch(n){case 'oe_get_state':r={data:d.mis,revision:d.revision,role:'admin'};break;case 'oe_save_state':d.mis=a.p_data;d.revision++;r={data:d.mis,revision:d.revision,role:'admin'};break;case 'oe_role':r='admin';break;case 'oe_staff_list':case 'oe_audit_log':r=[];break;case 'oe_hub_staff':r={items:[],actions:[],settings:{data:{global:{},students:{}},revision:1},role:'admin'};break;
case 'oh_staff':case 'oh_student':r={role:'admin',school:d.mis.school,topics:source.topics,classes:d.mis.classes,students:d.mis.students,student:d.mis.students[0],assignments:d.assignments.filter(x=>!x.archived),progress:d.progress};break;
case 'oh_create':{const qs=source.questions.filter(q=>a.p_topics.includes(q.topic)).slice(0,a.p_count);if(qs.length<a.p_count)throw Error('The demo has a smaller question selection. Reduce the question count or add topics.');const x={id:id(),class_id:a.p_class,title:a.p_title,due_at:a.p_due,question_ids:qs.map(q=>q.id),archived:false};d.assignments.unshift(x);r=x.id;break}
case 'oh_archive':d.assignments.find(x=>x.id===a.p_id).archived=true;break;
case 'oh_save':case 'oh_open':{const assignment=d.assignments.find(x=>x.id===a.p_id);let p=d.progress.find(x=>x.assignment_id===a.p_id);if(!p){p={assignment_id:a.p_id,student_id:d.mis.students[0].id,answers:{},submitted_at:null,score:null};d.progress.push(p)}if(n==='oh_save'){if(p.submitted_at)throw Error('Already submitted.');p.answers=a.p_answers;if(a.p_submit){if(assignment.question_ids.some(i=>p.answers[i]===undefined))throw Error('Answer every question first.');p.submitted_at=new Date().toISOString();p.score=assignment.question_ids.filter(i=>p.answers[i]===source.questions.find(q=>q.id===i).correct).length}}r={assignment,...p,questions:source.questions.filter(q=>assignment.question_ids.includes(q.id)).map(q=>({...q,topicTitle:source.topics.find(t=>t.id===q.topic)?.title}))};break}
case 'ss_staff':r=d.sixth;break;case 'ss_student':r=own();break;
case 'ss_settings_save':d.sixth.settings.choices_open=a.p_open;break;
case 'ss_choose':{if(!d.sixth.settings.choices_open)throw Error('Subject choices are closed.');if(a.p_subjects.length!==5||a.p_subjects.filter(x=>source.subjects.find(s=>s.id===x)?.group_type==='core').length!==2)throw Error('Choose three options and two core subjects.');const p=d.sixth.students[0];d.sixth.enrolments=d.sixth.enrolments.filter(e=>e.student_id!==p.id);for(const sid of a.p_subjects)d.sixth.enrolments.push({student_id:p.id,class_id:d.sixth.classes.find(c=>c.subject_id===sid&&c.year===p.year).id});r=own();break}
case 'ss_import':{const ids=[];for(const name of a.p_names){const p={...name,id:id(),year:a.p_year,login_code:id().replaceAll('-','').toUpperCase(),access_code:'SF-'+id().slice(0,8),gcse_notes:a.p_gcse||'',archived:false};d.sixth.students.push(p);ids.push(p.id);for(const sid of a.p_subjects||[])d.sixth.enrolments.push({student_id:p.id,class_id:d.sixth.classes.find(c=>c.subject_id===sid&&c.year===p.year).id})}r={imported:ids.length,skipped:0,ids};break}
case 'ss_notice':{const x={id:a.p_id||id(),title:a.p_title,body:a.p_body,year:a.p_year||null,published:a.p_published!==false,created_at:new Date().toISOString()};d.sixth.notices=d.sixth.notices.filter(n=>n.id!==x.id);d.sixth.notices.unshift(x);r=x.id;break}
case 'ss_register':for(const m of a.p_marks){d.sixth.attendance=d.sixth.attendance.filter(x=>!(x.student_id===m.id&&x.date===a.p_date&&x.session===a.p_session));d.sixth.attendance.push({student_id:m.id,date:a.p_date,session:a.p_session,mark:m.mark,note:m.note})}break;
default:throw Error('This demo previews this feature. Use an approved school account to save it.');}save();return structuredClone(r)}
